services:
  metadata-server-dev:
    image: dim145/metadata-server:dev
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata-server-dev
    ports:
      - "8080:80"
    environment:
      TVDB_API_KEY: "xxx"
      METADATA_SERVER_FOR: "sonarr"
      REDIS_HOST: redis
      LANGS_FALLBACK: fra,eng
      INCLUDE_ADULT_CONTENT: true
      USE_TMDB_FOR_SONARR: false # active tmdb. ne pas activé pour une instance existante de sonarr. ref au Readme.md
    volumes:
      - ./data:/data


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-insights:
    image: redis/redisinsight
    container_name: redis-insights
    ports:
      - '5540:5540'
    volumes:
      - redis_insights_data:/data
    depends_on:
      - redis

volumes:
  redis_data:
  redis_insights_data:
